# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-01-12 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktest_ORM', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookinfo',
            old_name='bpud_data',
            new_name='bpud_date',
        ),
        migrations.AlterField(
            model_name='bookinfo',
            name='bcomment',
            field=models.IntegerField(default=0, verbose_name='评论量'),
        ),
        migrations.AlterField(
            model_name='bookinfo',
            name='bread',
            field=models.IntegerField(default=0, verbose_name='阅读量'),
        ),
    ]
