# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-01-12 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatienceInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=20, verbose_name='名字')),
                ('pprice', models.IntegerField(default=10, verbose_name='价格')),
                ('pcomment', models.IntegerField(default=0, verbose_name='评论量')),
                ('psales', models.IntegerField(default=100, verbose_name='销量')),
                ('pdescribe', models.CharField(max_length=200, verbose_name='描述信息')),
            ],
            options={
                'verbose_name': '美多',
                'verbose_name_plural': '美多',
                'db_table': 'tb_patience',
            },
        ),
    ]
